# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AutomatedCulvertAnalysisWorkflow
                                 A QGIS plugin
 Culvert Identification and Characterization from Remote Sensing Data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-09-24
        copyright            : (C) 2024 by Water Resources Solutions, LLC
        email                : asprague@wrs-r.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Water Resources Solutions, LLC'
__date__ = '2024-09-24'
__copyright__ = '(C) 2024 by Water Resources Solutions, LLC'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AutomatedCulvertAnalysisWorkflow class from file AutomatedCulvertAnalysisWorkflow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .automated_culvert_analysis_workflow import AutomatedCulvertAnalysisWorkflowPlugin
    return AutomatedCulvertAnalysisWorkflowPlugin(iface)
